### ISSUE TITLE
드론 조종을 위한 UI

### ISSUE THREAD

**Issue by leesungbin** [hijackdrone/hijackdrone-rn#16]
## 어떤 형태여야하는가
![image](https://user-images.githubusercontent.com/25934842/59905379-076ed580-9441-11e9-9932-75dee59d45f5.png)
*시중 조종 어플 같은 형태가 좋을까.
*RC카 같이 일정한 방향으로만 조종할 수 있도록 해야할까.
*게임 진행 방향과 같이 고려해야함.
*하계 훈련 후 진행

**Comment by leesungbin** [comment]
* draggable element 만들기 : https://moduscreate.com/blog/animated_drag_and_drop_with_react_native/

**Comment by leesungbin** [comment]
#22 에서 진행중

**Comment by drawnby** [comment]
Good
